#!/bin/bash
# It is part of startlxde
# Launch DBus if needed
if test -z "$DBUS_SESSION_BUS_ADDRESS"; then
	if which dbus-launch >/dev/null; then
		eval "$(dbus-launch --sh-syntax --exit-with-session)"
	fi
else
	if which dbus-update-activation-environment >/dev/null; then
		dbus-update-activation-environment --systemd --all
	fi
fi

export XDG_MENU_PREFIX="pantheon-"
export XDG_CURRENT_DESKTOP="PANTHEON"
export XDG_SESSION_DESKTOP="PANTHEON"
if [[ -f ~/.config/pantheon-wm ]] ; then
    bash ~/.config/pantheon-wm &
else
    gala &
fi
{
cat << EOF
org.gnome.SettingsDaemon.A11ySettings
org.gnome.SettingsDaemon.Color
org.gnome.SettingsDaemon.Datetime
org.gnome.SettingsDaemon.Housekeeping
org.gnome.SettingsDaemon.Keyboard
org.gnome.SettingsDaemon.MediaKeys
org.gnome.SettingsDaemon.Power
org.gnome.SettingsDaemon.PrintNotifications
org.gnome.SettingsDaemon.Rfkill
org.gnome.SettingsDaemon.Sharing
org.gnome.SettingsDaemon.Smartcard
org.gnome.SettingsDaemon.Sound
org.gnome.SettingsDaemon.Wacom
org.gnome.SettingsDaemon.XSettings
EOF
}  | while read line ; do
	if [[ -f /usr/share/applications/$line.desktop ]] 
 then
		$(cat /usr/share/applications/$line.desktop | grep "Exec=" | sed "s/^Exec=//g") &	
	elif [[ -f /etc/xdg/autostart/$line.desktop ]]
 then
		$(cat /etc/xdg/autostart/$line.desktop | grep "Exec=" | sed "s/^Exec=//g") &
	else
		echo $line Not found
	fi
done
xdgrun(){
	file="$XDG_DIR/$1"
	if cat $file | grep  "NotShowIn" | grep -i "$XDG_SESSION_DESKTOP" &>/dev/null
 then
		echo "Skip: $1"
	elif cat $file | grep  "OnlyShowIn" | grep -vi "$XDG_SESSION_DESKTOP" &>/dev/null
 then
		echo "Skip: $1"
	else
		$(cat $file | grep "^Exec=" | sed "s/^Exec=//g") &
	fi

}

#Run autostart
for dir in /etc/xdg/autostart ~/.local/share/autostart
do
	ls $dir | while read name
	do
		XDG_DIR="$dir" xdgrun $name
	done
done
# Infinitive sleep
exec sleep inf
